variable "GITHUB_SYNC_IN_USERNAME" {
  # ENV:TF_VAR_GITHUB_SYNC_IN_USERNAME
  type = string
}

variable "GITHUB_SYNC_IN_PASSWORD" {
  # ENV:TF_VAR_GITHUB_SYNC_IN_PASSWORD
  type = string
}

variable "GITLAB_GROUP_ID_JEREMY_SHARED" {
  default = 57354115
}